"""report_pdf.py — Generate a structured PDF report for a Playwright test run."""

import io
import json
from datetime import datetime

from fpdf import FPDF

import db

# ── Color palette ────────────────────────────────────────────────────────────
WHITE      = (255, 255, 255)
BG_LIGHT   = (249, 250, 251)
BRAND      = (37, 99, 235)
BRAND_LIGHT= (239, 246, 255)
SUCCESS    = (22, 163, 74)
SUCCESS_BG = (240, 253, 244)
ERROR      = (220, 38, 38)
ERROR_BG   = (254, 242, 242)
WARNING    = (217, 119, 6)
WARNING_BG = (255, 251, 235)
GRAY_700   = (55, 65, 81)
GRAY_500   = (107, 114, 128)
GRAY_400   = (156, 163, 175)
GRAY_200   = (229, 231, 235)
GRAY_100   = (243, 244, 246)
TEXT_DARK  = (17, 24, 39)


class ReportPDF(FPDF):
    def __init__(self, run, results):
        super().__init__('P', 'mm', 'A4')
        self.run = run
        self.results = results
        self.set_auto_page_break(auto=True, margin=20)

    def header(self):
        if self.page_no() == 1:
            return
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(*GRAY_400)
        self.cell(0, 6, f'Run #{self.run["id"]} Report', align='L')
        self.cell(0, 6, f'Page {self.page_no()}', align='R', new_x='LMARGIN', new_y='NEXT')
        self.set_draw_color(*GRAY_200)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 7)
        self.set_text_color(*GRAY_400)
        self.cell(0, 8, 'Generated by Prompt Optimization Lab', align='L')
        self.cell(0, 8, f'Page {self.page_no()}/{{nb}}', align='R')

    def _rounded_rect_fill(self, x, y, w, h, r, color):
        self.set_fill_color(*color)
        self.rect(x, y, w, h, style='F', round_corners=True, corner_radius=r)

    def _safe_text(self, txt):
        if not txt:
            return ''
        return txt.encode('latin-1', 'replace').decode('latin-1')


def generate_report(run_id: int) -> bytes:
    run = db.get_playwright_run(run_id)
    if not run:
        raise ValueError(f"Run #{run_id} not found")
    results = db.get_playwright_results(run_id)

    pdf = ReportPDF(run, results)
    pdf.alias_nb_pages()
    pdf.add_page()

    _draw_cover(pdf, run, results)
    _draw_metrics(pdf, run, results)
    _draw_test_cases(pdf, results)
    _draw_summary(pdf, run, results)

    buf = io.BytesIO()
    pdf.output(buf)
    return buf.getvalue()


def _draw_cover(pdf: ReportPDF, run, results):
    pdf.set_y(20)

    pdf.set_font('Helvetica', 'B', 22)
    pdf.set_text_color(*BRAND)
    pdf.cell(0, 12, pdf._safe_text('Live Bot Test Report'), align='C', new_x='LMARGIN', new_y='NEXT')

    pdf.set_font('Helvetica', '', 10)
    pdf.set_text_color(*GRAY_500)
    pdf.cell(0, 7, pdf._safe_text(f'Run #{run["id"]}'), align='C', new_x='LMARGIN', new_y='NEXT')

    pdf.ln(6)
    pdf.set_draw_color(*GRAY_200)
    pdf.line(60, pdf.get_y(), 150, pdf.get_y())
    pdf.ln(6)

    info_items = [
        ('Bot ID', run.get('bot_id', '—')),
        ('Mode', run.get('mode', '—')),
        ('Started', _fmt_dt(run.get('started_at', ''))),
        ('Ended', _fmt_dt(run.get('ended_at', ''))),
        ('Status', run.get('status', '—').upper()),
    ]

    pdf.set_font('Helvetica', '', 9)
    for label, value in info_items:
        pdf.set_text_color(*GRAY_500)
        pdf.cell(40, 6, pdf._safe_text(f'{label}:'), align='R')
        pdf.set_text_color(*TEXT_DARK)
        pdf.set_font('Helvetica', 'B', 9)
        pdf.cell(0, 6, pdf._safe_text(f'  {value}'), align='L', new_x='LMARGIN', new_y='NEXT')
        pdf.set_font('Helvetica', '', 9)

    pdf.ln(6)


def _draw_metrics(pdf: ReportPDF, run, results):
    total  = len(results)
    passed = sum(1 for r in results if r['overall'] == 'PASS')
    failed = sum(1 for r in results if r['overall'] == 'FAIL')
    errors = sum(1 for r in results if r['overall'] not in ('PASS', 'FAIL'))
    pct    = round(passed / total * 100, 1) if total else 0

    start_y = pdf.get_y()

    pdf.set_font('Helvetica', 'B', 11)
    pdf.set_text_color(*TEXT_DARK)
    pdf.cell(0, 8, 'Test Results Overview', new_x='LMARGIN', new_y='NEXT')
    pdf.ln(2)

    card_w = 43
    card_h = 28
    gap    = 4
    x0     = 12

    cards = [
        ('Total Tests', str(total), BRAND, BRAND_LIGHT),
        ('Passed', str(passed), SUCCESS, SUCCESS_BG),
        ('Failed', str(failed), ERROR, ERROR_BG),
        ('Pass Rate', f'{pct}%', _pct_color(pct), _pct_bg(pct)),
    ]

    cy = pdf.get_y()
    for i, (label, value, color, bg) in enumerate(cards):
        cx = x0 + i * (card_w + gap)
        pdf._rounded_rect_fill(cx, cy, card_w, card_h, 3, bg)
        pdf.set_xy(cx, cy + 4)
        pdf.set_font('Helvetica', '', 8)
        pdf.set_text_color(*GRAY_500)
        pdf.cell(card_w, 5, pdf._safe_text(label), align='C')
        pdf.set_xy(cx, cy + 11)
        pdf.set_font('Helvetica', 'B', 16)
        pdf.set_text_color(*color)
        pdf.cell(card_w, 10, pdf._safe_text(value), align='C')

    if errors > 0:
        cx = x0 + 4 * (card_w + gap)
        if cx + card_w <= 200:
            pdf._rounded_rect_fill(cx, cy, card_w, card_h, 3, WARNING_BG)
            pdf.set_xy(cx, cy + 4)
            pdf.set_font('Helvetica', '', 8)
            pdf.set_text_color(*GRAY_500)
            pdf.cell(card_w, 5, 'Errors', align='C')
            pdf.set_xy(cx, cy + 11)
            pdf.set_font('Helvetica', 'B', 16)
            pdf.set_text_color(*WARNING)
            pdf.cell(card_w, 10, str(errors), align='C')

    pdf.set_y(cy + card_h + 8)

    # Results bar
    bar_x = 12
    bar_w = 186
    bar_h = 6
    pdf._rounded_rect_fill(bar_x, pdf.get_y(), bar_w, bar_h, 2, GRAY_100)
    if total > 0:
        pass_w = max(1, bar_w * passed / total)
        fail_w = max(1, bar_w * failed / total) if failed else 0
        if passed:
            pdf._rounded_rect_fill(bar_x, pdf.get_y(), pass_w, bar_h, 2, SUCCESS)
        if failed:
            pdf._rounded_rect_fill(bar_x + pass_w, pdf.get_y(), fail_w, bar_h, 2, ERROR)

    pdf.ln(bar_h + 6)

    # Agent breakdown
    agents = {}
    for r in results:
        name = r.get('use_case_name', 'Unknown')
        if name not in agents:
            agents[name] = {'pass': 0, 'fail': 0, 'error': 0}
        if r['overall'] == 'PASS':
            agents[name]['pass'] += 1
        elif r['overall'] == 'FAIL':
            agents[name]['fail'] += 1
        else:
            agents[name]['error'] += 1

    if len(agents) > 1:
        pdf.set_font('Helvetica', 'B', 9)
        pdf.set_text_color(*TEXT_DARK)
        pdf.cell(0, 7, 'Results by Agent', new_x='LMARGIN', new_y='NEXT')
        pdf.ln(1)

        pdf.set_font('Helvetica', 'B', 8)
        pdf.set_text_color(*GRAY_500)
        pdf.set_fill_color(*GRAY_100)
        pdf.cell(90, 6, '  Agent', fill=True)
        pdf.cell(20, 6, 'Pass', align='C', fill=True)
        pdf.cell(20, 6, 'Fail', align='C', fill=True)
        pdf.cell(20, 6, 'Error', align='C', fill=True)
        pdf.cell(40, 6, 'Rate', align='C', fill=True, new_x='LMARGIN', new_y='NEXT')

        pdf.set_font('Helvetica', '', 8)
        for name, counts in agents.items():
            atotal = counts['pass'] + counts['fail'] + counts['error']
            rate = round(counts['pass'] / atotal * 100) if atotal else 0
            pdf.set_text_color(*TEXT_DARK)
            pdf.cell(90, 6, pdf._safe_text(f'  {name[:45]}'))
            pdf.set_text_color(*SUCCESS)
            pdf.cell(20, 6, str(counts['pass']), align='C')
            pdf.set_text_color(*ERROR)
            pdf.cell(20, 6, str(counts['fail']), align='C')
            pdf.set_text_color(*WARNING)
            pdf.cell(20, 6, str(counts['error']), align='C')
            pdf.set_text_color(*TEXT_DARK)
            pdf.cell(40, 6, f'{rate}%', align='C', new_x='LMARGIN', new_y='NEXT')

        pdf.ln(4)

    pdf.set_draw_color(*GRAY_200)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(4)


def _draw_test_cases(pdf: ReportPDF, results):
    pdf.set_font('Helvetica', 'B', 13)
    pdf.set_text_color(*TEXT_DARK)
    pdf.cell(0, 10, 'Test Case Details', new_x='LMARGIN', new_y='NEXT')
    pdf.ln(2)

    for idx, r in enumerate(results):
        _draw_one_test(pdf, r, idx + 1)


def _draw_one_test(pdf: ReportPDF, result, num):
    if pdf.get_y() > 240:
        pdf.add_page()

    overall = result['overall']
    is_pass = overall == 'PASS'
    border_color = SUCCESS if is_pass else ERROR if overall == 'FAIL' else WARNING
    bg_color = SUCCESS_BG if is_pass else ERROR_BG if overall == 'FAIL' else WARNING_BG

    # Test header card
    y0 = pdf.get_y()
    pdf._rounded_rect_fill(10, y0, 190, 14, 3, bg_color)
    pdf.set_xy(14, y0 + 2)

    # Status indicator
    pdf.set_fill_color(*border_color)
    pdf.circle(16, y0 + 7, 2.5, style='F')

    pdf.set_xy(22, y0 + 2)
    pdf.set_font('Helvetica', 'B', 10)
    pdf.set_text_color(*TEXT_DARK)
    pdf.cell(120, 5, pdf._safe_text(f'{result.get("test_id", f"PT-{num:03d}")} — {result.get("name", "")}'))

    pdf.set_xy(160, y0 + 2)
    pdf.set_font('Helvetica', 'B', 10)
    pdf.set_text_color(*border_color)
    pdf.cell(36, 5, overall, align='R')

    # Agent name
    pdf.set_xy(22, y0 + 8)
    pdf.set_font('Helvetica', 'I', 7.5)
    pdf.set_text_color(*GRAY_500)
    pdf.cell(0, 4, pdf._safe_text(f'Agent: {result.get("use_case_name", "—")}'))

    pdf.set_y(y0 + 16)

    # Summary
    summary = result.get('summary', '')
    if summary:
        pdf.set_font('Helvetica', 'I', 8)
        pdf.set_text_color(*GRAY_700)
        pdf.multi_cell(186, 4.5, pdf._safe_text(f'Judge: {summary}'), new_x='LMARGIN', new_y='NEXT')
        pdf.ln(2)

    # Conversation turns
    turns = result.get('turns', [])
    if turns:
        pdf.set_font('Helvetica', 'B', 8)
        pdf.set_text_color(*GRAY_500)
        pdf.cell(0, 5, 'CONVERSATION', new_x='LMARGIN', new_y='NEXT')
        pdf.ln(1)

        for t in turns:
            _draw_turn(pdf, t)

    pdf.ln(4)
    pdf.set_draw_color(*GRAY_200)
    pdf.dashed_line(10, pdf.get_y(), 200, pdf.get_y(), dash_length=2, space_length=2)
    pdf.ln(5)


def _draw_turn(pdf: ReportPDF, turn):
    if pdf.get_y() > 260:
        pdf.add_page()

    turn_num = turn.get('turn', '?')

    # User message
    uy = pdf.get_y()
    pdf._rounded_rect_fill(14, uy, 90, 5, 1.5, BRAND_LIGHT)
    pdf.set_xy(16, uy + 0.5)
    pdf.set_font('Helvetica', 'B', 7)
    pdf.set_text_color(*BRAND)
    pdf.cell(0, 4, pdf._safe_text(f'Turn {turn_num} - User'))
    pdf.set_y(uy + 6)

    pdf.set_x(16)
    pdf.set_font('Helvetica', '', 8.5)
    pdf.set_text_color(*TEXT_DARK)
    user_text = turn.get('user', '') or '(empty)'
    pdf.multi_cell(178, 4.5, pdf._safe_text(user_text), new_x='LMARGIN', new_y='NEXT')
    pdf.ln(1.5)

    # Expected (if present)
    expected = turn.get('expected', '')
    if expected:
        pdf.set_x(16)
        pdf.set_font('Helvetica', 'I', 7.5)
        pdf.set_text_color(*GRAY_500)
        pdf.multi_cell(178, 4, pdf._safe_text(f'Expected: {expected}'), new_x='LMARGIN', new_y='NEXT')
        pdf.ln(1)

    # Bot response
    by = pdf.get_y()
    pdf._rounded_rect_fill(14, by, 90, 5, 1.5, SUCCESS_BG)
    pdf.set_xy(16, by + 0.5)
    pdf.set_font('Helvetica', 'B', 7)
    pdf.set_text_color(*SUCCESS)
    pdf.cell(0, 4, 'Bot')
    pdf.set_y(by + 6)

    pdf.set_x(16)
    pdf.set_font('Helvetica', '', 8.5)
    pdf.set_text_color(*TEXT_DARK)
    actual = turn.get('actual', '') or '(no response captured)'
    pdf.multi_cell(178, 4.5, pdf._safe_text(actual), new_x='LMARGIN', new_y='NEXT')
    pdf.ln(2.5)


def _draw_summary(pdf: ReportPDF, run, results):
    pdf.add_page()

    pdf.set_font('Helvetica', 'B', 13)
    pdf.set_text_color(*TEXT_DARK)
    pdf.cell(0, 10, 'Run Summary', new_x='LMARGIN', new_y='NEXT')
    pdf.ln(2)

    total  = len(results)
    passed = sum(1 for r in results if r['overall'] == 'PASS')
    failed = sum(1 for r in results if r['overall'] == 'FAIL')
    errors = total - passed - failed
    pct    = round(passed / total * 100, 1) if total else 0

    # Summary box
    box_y = pdf.get_y()
    box_color = SUCCESS_BG if pct == 100 else ERROR_BG if pct < 50 else WARNING_BG
    pdf._rounded_rect_fill(10, box_y, 190, 22, 3, box_color)

    pdf.set_xy(16, box_y + 4)
    pdf.set_font('Helvetica', 'B', 14)
    result_color = SUCCESS if pct == 100 else ERROR if pct < 50 else WARNING
    pdf.set_text_color(*result_color)
    if pct == 100:
        verdict = 'ALL TESTS PASSED'
    elif pct >= 50:
        verdict = f'{passed}/{total} TESTS PASSED ({pct}%)'
    else:
        verdict = f'MOST TESTS FAILED — {passed}/{total} passed ({pct}%)'
    pdf.cell(0, 7, pdf._safe_text(verdict))

    pdf.set_xy(16, box_y + 13)
    pdf.set_font('Helvetica', '', 8)
    pdf.set_text_color(*GRAY_700)
    duration = _calc_duration(run.get('started_at', ''), run.get('ended_at', ''))
    pdf.cell(0, 5, pdf._safe_text(f'Completed in {duration} | Mode: {run.get("mode", "—")} | Bot: {run.get("bot_id", "—")}'))

    pdf.set_y(box_y + 28)

    # Detailed breakdown table
    pdf.set_font('Helvetica', 'B', 9)
    pdf.set_text_color(*TEXT_DARK)
    pdf.cell(0, 7, 'Detailed Results', new_x='LMARGIN', new_y='NEXT')
    pdf.ln(1)

    # Table header
    pdf.set_font('Helvetica', 'B', 8)
    pdf.set_text_color(*GRAY_500)
    pdf.set_fill_color(*GRAY_100)
    pdf.cell(22, 6, '  ID', fill=True)
    pdf.cell(80, 6, 'Test Name', fill=True)
    pdf.cell(44, 6, 'Agent', fill=True)
    pdf.cell(20, 6, 'Result', align='C', fill=True)
    pdf.cell(24, 6, 'Turns', align='C', fill=True, new_x='LMARGIN', new_y='NEXT')

    pdf.set_font('Helvetica', '', 8)
    for r in results:
        is_pass = r['overall'] == 'PASS'
        pdf.set_text_color(*TEXT_DARK)
        pdf.cell(22, 5.5, pdf._safe_text(f'  {r.get("test_id", "?")}'))
        pdf.cell(80, 5.5, pdf._safe_text(r.get('name', '')[:42]))
        pdf.set_text_color(*GRAY_500)
        pdf.cell(44, 5.5, pdf._safe_text(r.get('use_case_name', '—')[:22]))
        color = SUCCESS if is_pass else ERROR if r['overall'] == 'FAIL' else WARNING
        pdf.set_text_color(*color)
        pdf.set_font('Helvetica', 'B', 8)
        pdf.cell(20, 5.5, r['overall'], align='C')
        pdf.set_font('Helvetica', '', 8)
        pdf.set_text_color(*TEXT_DARK)
        pdf.cell(24, 5.5, str(len(r.get('turns', []))), align='C', new_x='LMARGIN', new_y='NEXT')

        # Separator line
        pdf.set_draw_color(*GRAY_200)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())

    pdf.ln(8)

    # Failed tests detail
    failed_results = [r for r in results if r['overall'] != 'PASS']
    if failed_results:
        pdf.set_font('Helvetica', 'B', 9)
        pdf.set_text_color(*ERROR)
        pdf.cell(0, 7, pdf._safe_text(f'Failed / Error Tests ({len(failed_results)})'), new_x='LMARGIN', new_y='NEXT')
        pdf.ln(1)

        for r in failed_results:
            if pdf.get_y() > 260:
                pdf.add_page()
            pdf.set_font('Helvetica', 'B', 8)
            pdf.set_text_color(*TEXT_DARK)
            pdf.cell(0, 5, pdf._safe_text(f'{r.get("test_id", "?")} — {r.get("name", "")}'), new_x='LMARGIN', new_y='NEXT')
            if r.get('summary'):
                pdf.set_font('Helvetica', 'I', 7.5)
                pdf.set_text_color(*GRAY_700)
                pdf.multi_cell(186, 4, pdf._safe_text(f'  {r["summary"]}'), new_x='LMARGIN', new_y='NEXT')
            pdf.ln(2)

    # Footer note
    pdf.ln(6)
    pdf.set_draw_color(*GRAY_200)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(4)
    pdf.set_font('Helvetica', 'I', 7.5)
    pdf.set_text_color(*GRAY_400)
    pdf.cell(0, 5, pdf._safe_text(f'Report generated on {datetime.now().strftime("%Y-%m-%d %H:%M:%S")} by Prompt Optimization Lab'), align='C')


# ── Helpers ──────────────────────────────────────────────────────────────────

def _fmt_dt(iso_str):
    if not iso_str:
        return '—'
    try:
        dt = datetime.fromisoformat(iso_str.replace('Z', '+00:00'))
        return dt.strftime('%b %d, %Y at %H:%M')
    except Exception:
        return iso_str


def _calc_duration(start, end):
    if not start or not end:
        return '—'
    try:
        s = datetime.fromisoformat(start.replace('Z', '+00:00'))
        e = datetime.fromisoformat(end.replace('Z', '+00:00'))
        delta = e - s
        secs = int(delta.total_seconds())
        if secs < 60:
            return f'{secs}s'
        mins = secs // 60
        secs = secs % 60
        return f'{mins}m {secs}s'
    except Exception:
        return '—'


def _pct_color(pct):
    if pct >= 80:
        return SUCCESS
    if pct >= 50:
        return WARNING
    return ERROR


def _pct_bg(pct):
    if pct >= 80:
        return SUCCESS_BG
    if pct >= 50:
        return WARNING_BG
    return ERROR_BG
