"""
Yellow.ai Prompt Testing Framework
===================================
Sends test conversations to the bot via the Yellow.ai REST API and
retrieves full conversation transcripts for Claude to evaluate.

Usage:
    python test_runner.py --config bot_config.json --tests tests.json --output test_results/
    python test_runner.py --config bot_config.json --tests tests.json --output test_results/ --only TC-003,TC-007

Input files:
    bot_config.json  — bot credentials (bot_id, api_key, base_url)
    tests.json       — test suite generated by Claude in Phase 2

Output:
    test_results/TC-NNN_transcript.json  — full conversation log per test case
    test_results/run_summary.json        — pass/fail status and errors per run
"""

import argparse
import json
import os
import random
import time
import sys
from datetime import datetime

import requests


# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

def load_config(config_path: str) -> dict:
    with open(config_path) as f:
        cfg = json.load(f)
    required = ["bot_id", "api_key", "base_url"]
    for key in required:
        if not cfg.get(key):
            raise ValueError(f"Missing required field in bot_config.json: {key}")
    return cfg


def load_tests(tests_path: str, only: list[str] | None = None) -> list[dict]:
    with open(tests_path) as f:
        suite = json.load(f)
    if only:
        suite = [tc for tc in suite if tc["id"] in only]
    return suite


# ---------------------------------------------------------------------------
# Session helpers
# ---------------------------------------------------------------------------

def generate_uid() -> str:
    """Generate a unique 28-digit numeric sender ID."""
    return "".join([str(random.randint(0, 9)) for _ in range(28)])


def now_ms() -> int:
    """Current Unix timestamp in milliseconds."""
    return int(time.time() * 1000)


# ---------------------------------------------------------------------------
# API 1 — Send Message
# ---------------------------------------------------------------------------

def send_message(
    bot_id: str,
    api_key: str,
    base_url: str,
    uid: str,
    message: str,
    retries: int = 3,
) -> dict:
    """
    Send a user message to the bot and return the bot's reply.

    Returns:
        {
            "bot_messages": ["text of bot reply", ...],
            "session_id": "abc123..." or None,
            "raw_events": [...]   # all parsed SSE events
        }
    """
    url = f"{base_url}/integrations/yellowmessenger/receive/v3?bottype=production&bot={bot_id}"
    headers = {
        "Content-Type": "application/json",
        "x-api-key": api_key,
        "x-bot-env": "production",
        "accept": "*/*",
        "origin": "https://nexus.yellow.ai",
    }
    body = {
        "type": "threads.message",
        "from": uid,
        "to": bot_id,
        "source": "yellowmessenger",
        "widgetVersion": "v3",
        "stream": True,
        "data": {
            "message": message,
            "messageId": now_ms(),
            "pageUrl": "https://nexus.yellow.ai",
            "isSensitiveInfo": False,
            "subSource": None,
        },
    }

    last_error = None
    for attempt in range(1, retries + 1):
        try:
            resp = requests.post(url, headers=headers, json=body, stream=True, timeout=30)
            if resp.status_code != 200:
                raise RuntimeError(f"HTTP {resp.status_code}: {resp.text[:200]}")

            bot_messages = []
            session_id = None
            raw_events = []

            for raw_line in resp.iter_lines():
                if not raw_line:
                    continue
                line = raw_line.decode("utf-8") if isinstance(raw_line, bytes) else raw_line

                if line.startswith("data:"):
                    payload = line[5:].strip()
                    if not payload or payload == "[DONE]":
                        continue
                    try:
                        event = json.loads(payload)
                        raw_events.append(event)

                        # Extract bot message text — adjust field names if needed
                        for field in ("message", "text", "reply", "botReply"):
                            if field in event and isinstance(event[field], str):
                                if event[field].strip():
                                    bot_messages.append(event[field])
                                break

                        # Capture sessionId
                        for field in ("sessionId", "session_id", "sid"):
                            if field in event and event[field]:
                                session_id = session_id or event[field]
                                break

                    except json.JSONDecodeError:
                        pass  # non-JSON SSE line, skip

            return {
                "bot_messages": bot_messages,
                "session_id": session_id,
                "raw_events": raw_events,
            }

        except Exception as e:
            last_error = str(e)
            if attempt < retries:
                print(f"  ⚠ send_message attempt {attempt} failed: {e}. Retrying in 5s...")
                time.sleep(5)

    return {
        "bot_messages": [],
        "session_id": None,
        "raw_events": [],
        "error": f"All {retries} attempts failed. Last error: {last_error}",
    }


# ---------------------------------------------------------------------------
# API 2 — Conversation Logs
# ---------------------------------------------------------------------------

def get_conversation_logs(
    bot_id: str,
    api_key: str,
    base_url: str,
    uid: str,
    session_id: str,
    retries: int = 3,
) -> list[dict]:
    """
    Retrieve the full conversation log for a session.
    Returns messages in CHRONOLOGICAL order (reversed from API, which returns [0]=latest).
    """
    url = f"{base_url}/api/agents/data/messages"
    params = {"bot": bot_id, "uid": uid, "sessionId": session_id}
    headers = {
        "accept": "application/json",
        "x-api-key": api_key,
        "origin": "https://nexus.yellow.ai",
    }

    last_error = None
    for attempt in range(1, retries + 1):
        try:
            resp = requests.get(url, headers=headers, params=params, timeout=20)
            if resp.status_code != 200:
                raise RuntimeError(f"HTTP {resp.status_code}: {resp.text[:200]}")

            data = resp.json()
            if not isinstance(data, list):
                # Some endpoints wrap the array
                data = data.get("messages", data.get("data", []))

            if not data:
                if attempt < retries:
                    print(f"  ⚠ Logs empty on attempt {attempt}. Waiting 5s for logs to settle...")
                    time.sleep(5)
                    continue

            # Reverse so index 0 = first message (chronological)
            return list(reversed(data))

        except Exception as e:
            last_error = str(e)
            if attempt < retries:
                print(f"  ⚠ get_conversation_logs attempt {attempt} failed: {e}. Retrying in 5s...")
                time.sleep(5)

    print(f"  ✗ Could not retrieve logs. Last error: {last_error}")
    return []


# ---------------------------------------------------------------------------
# Test case runner
# ---------------------------------------------------------------------------

def run_test_case(config: dict, test_case: dict) -> dict:
    """
    Execute a single test case: send all turns, collect transcript.

    test_case format:
    {
        "id": "TC-001",
        "name": "Happy path — book appointment",
        "conversation_script": ["hi", "book appointment", "Employee Only", ...]
    }

    Returns a result dict with uid, session_id, transcript, and status.
    """
    bot_id = config["bot_id"]
    api_key = config["api_key"]
    base_url = config["base_url"]

    tc_id = test_case["id"]
    script = test_case["conversation_script"]

    uid = generate_uid()
    session_id = None
    turns = []
    status = "PASS"  # optimistic; set to ERROR if API fails

    print(f"\n  UID: {uid}")

    for i, user_message in enumerate(script):
        print(f"  Turn {i+1}: User → \"{user_message}\"")

        result = send_message(bot_id, api_key, base_url, uid, user_message)

        if result.get("error"):
            print(f"  ✗ API error on turn {i+1}: {result['error']}")
            status = "ERROR"
            turns.append({
                "turn": i + 1,
                "user": user_message,
                "bot": [],
                "raw_events": [],
                "error": result["error"],
            })
            break

        # Capture sessionId from first successful response
        if not session_id and result.get("session_id"):
            session_id = result["session_id"]
            print(f"  Session ID captured: {session_id}")

        bot_reply_preview = " | ".join(result["bot_messages"])[:120] if result["bot_messages"] else "(no text captured)"
        print(f"  Turn {i+1}: Bot  → \"{bot_reply_preview}\"")

        turns.append({
            "turn": i + 1,
            "user": user_message,
            "bot": result["bot_messages"],
            "raw_events": result["raw_events"],
        })

        # Wait between turns
        time.sleep(2)

    # Retrieve full structured transcript
    transcript = []
    if session_id and status != "ERROR":
        print(f"  Fetching conversation log...")
        time.sleep(3)  # allow logs to settle
        transcript = get_conversation_logs(bot_id, api_key, base_url, uid, session_id)
        if not transcript:
            print(f"  ⚠ Transcript empty — falling back to stream turns only")

    return {
        "id": tc_id,
        "name": test_case.get("name", ""),
        "uid": uid,
        "session_id": session_id,
        "status": status,
        "turns": turns,           # stream-captured turns (real-time)
        "transcript": transcript, # full structured log from API 2 (for evaluation)
        "timestamp": datetime.utcnow().isoformat() + "Z",
    }


# ---------------------------------------------------------------------------
# Test suite runner
# ---------------------------------------------------------------------------

def run_test_suite(config: dict, test_cases: list[dict], output_dir: str) -> dict:
    """
    Run all test cases sequentially and write results to output_dir.
    Returns a summary dict.
    """
    os.makedirs(output_dir, exist_ok=True)
    summary = {
        "run_timestamp": datetime.utcnow().isoformat() + "Z",
        "bot_id": config["bot_id"],
        "total": len(test_cases),
        "completed": 0,
        "errors": 0,
        "results": {},
    }

    for tc in test_cases:
        tc_id = tc["id"]
        print(f"\n{'='*60}")
        print(f"Running {tc_id}: {tc.get('name', '')}")
        print(f"{'='*60}")

        result = run_test_case(config, tc)
        summary["completed"] += 1
        if result["status"] == "ERROR":
            summary["errors"] += 1

        summary["results"][tc_id] = {
            "status": result["status"],
            "session_id": result["session_id"],
            "uid": result["uid"],
        }

        # Write transcript to file
        out_path = os.path.join(output_dir, f"{tc_id}_transcript.json")
        with open(out_path, "w") as f:
            json.dump(result, f, indent=2)
        print(f"  → Transcript saved: {out_path}")

        # Gap between test cases
        if tc != test_cases[-1]:
            print("  Waiting 3s before next test case...")
            time.sleep(3)

    # Write summary
    summary_path = os.path.join(output_dir, "run_summary.json")
    with open(summary_path, "w") as f:
        json.dump(summary, f, indent=2)

    print(f"\n{'='*60}")
    print(f"Run complete. {summary['completed']}/{summary['total']} test cases executed.")
    print(f"Errors: {summary['errors']}")
    print(f"Summary: {summary_path}")
    print(f"{'='*60}")

    return summary


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="Yellow.ai Prompt Test Runner")
    parser.add_argument("--config", required=True, help="Path to bot_config.json")
    parser.add_argument("--tests", required=True, help="Path to tests.json")
    parser.add_argument("--output", required=True, help="Output directory for transcripts")
    parser.add_argument(
        "--only",
        default=None,
        help="Comma-separated list of test case IDs to run (e.g. TC-003,TC-007)",
    )
    args = parser.parse_args()

    # Load config
    try:
        config = load_config(args.config)
    except Exception as e:
        print(f"✗ Failed to load config: {e}")
        sys.exit(1)

    # Load test cases
    only = [x.strip() for x in args.only.split(",")] if args.only else None
    try:
        test_cases = load_tests(args.tests, only=only)
    except Exception as e:
        print(f"✗ Failed to load tests: {e}")
        sys.exit(1)

    if not test_cases:
        print("✗ No test cases to run.")
        sys.exit(1)

    print(f"Bot ID: {config['bot_id']}")
    print(f"Base URL: {config['base_url']}")
    print(f"Test cases to run: {len(test_cases)}")

    run_test_suite(config, test_cases, args.output)


if __name__ == "__main__":
    main()
